type ReduxTypes = string;

const COURTS_FETCH_REQUESTED: ReduxTypes = 'COURTS_FETCH_REQUESTED';
const COURTS_FETCH_SUCCEEDED: ReduxTypes = 'COURTS_FETCH_SUCCEEDED';
const COURTS_FETCH_FAILED: ReduxTypes = 'COURTS_FETCH_FAILED';
const SCHOOLS_FETCH_REQUESTED: ReduxTypes = 'SCHOOLS_FETCH_REQUESTED';
const SCHOOLS_FETCH_SUCCEEDED: ReduxTypes = 'SCHOOLS_FETCH_SUCCEEDED';
const SCHOOLS_FETCH_FAILED: ReduxTypes = 'SCHOOLS_FETCH_FAILED';

export default {
  COURTS_FETCH_REQUESTED,
  COURTS_FETCH_SUCCEEDED,
  COURTS_FETCH_FAILED,
  SCHOOLS_FETCH_REQUESTED,
  SCHOOLS_FETCH_SUCCEEDED,
  SCHOOLS_FETCH_FAILED,
}